version: '3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sh4581
      MYSQL_DATABASE: habbit
      MYSQL_USER: sihanni
      MYSQL_PASSWORD: sh4581
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
